load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "utils",
    srcs = ["string.go"],
    cgo = True,
    importpath = "mosn.io/envoy-go-extension/pkg/utils",
    visibility = ["//visibility:public"],
)
