name: Build & Test Envoy
on:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run test-envoy
        run: ./ci/run_envoy_docker.sh make test-envoy 'BUILD_OPTS="--define=deprecated_features=disabled --define=wasm=disabled --config=gcc --jobs 1"'

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run build-envoy
        run: ./ci/run_envoy_docker.sh make build-envoy 'BUILD_OPTS="--define=wasm=disabled"'

