name: golangci
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          go_version: "1.18"
          golangci_lint_flags: "--disable-all --enable gofmt"
          fail_on_error: true
          level: error

  build-so:
    name: build-so
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Run build-so
        run: make build-so
